version: 2.1

defaults: &defaults
  working_directory: ~/auto
  docker:
    - image: circleci/node:8.14-browsers
  environment:
    TZ: '/usr/share/zoneinfo/America/Los_Angeles'

aliases:
  # Circle related commands
  - &restore-cache
    keys:
      # Find a cache corresponding to this specific package.json checksum
      # when this file is changed, this key will fail
      - auto-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
      - auto-{{ checksum "yarn.lock" }}
      # Find the most recent cache used from any branch
      - auto-
  - &save-cache
    key: auto-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
    paths:
      - ~/.cache/yarn
      - node_modules
  # Yarn commands
  - &yarn
    name: Install Dependencies
    command: yarn install --frozen-lockfile --non-interactive --cache-folder=~/.cache/yarn
  - &lint
    name: Lint
    command: yarn lint
  - &test
    name: Test
    command: yarn test

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: date
      - run: *yarn
      - save_cache: *save-cache
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto
      - run: *lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto
      - run: *test
      - run:
          name: Send CodeCov Results
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_KEY

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto
      - run:
          name: Build
          command: yarn build
      - run:
          name: Check PR for semVer label
          command: yarn semver:check
      - persist_to_workspace:
          root: .
          paths:
            - .

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Release
          command: yarn run release

  canary:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto
      - run:
          name: Canary
          command: yarn run release:canary

  publishDocs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto
      - run:
          name: Publish Docs
          command: yarn docs:publish

workflows:
  version: 2
  build_and_test:
    jobs:
      - install

      - lint:
          requires:
            - install

      - test:
          requires:
            - install

      - build:
          requires:
            - install

      - canary:
          requires:
            - build
            - test
            - lint
          filters:
            branches:
              ignore:
                - master

      - release:
          requires:
            - build
            - test
            - lint
          filters:
            branches:
              only:
                - master

      - publishDocs:
          requires:
            - release
          filters:
            branches:
              only:
                - master
