version: 2

defaults: &defaults
  working_directory: ~/auto-release
  docker:
    - image: circleci/node:8.14-browsers
  environment:
    TZ: '/usr/share/zoneinfo/America/Los_Angeles'

aliases:
  # Circle related commands
  - &restore-cache
    keys:
      # Find a cache corresponding to this specific package.json checksum
      # when this file is changed, this key will fail
      - auto-release-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
      - auto-release-{{ checksum "yarn.lock" }}
      # Find the most recent cache used from any branch
      - auto-release-
  - &save-cache
      key: auto-release-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
      paths:
        - ~/.cache/yarn
        - node_modules
  # Yarn commands
  - &yarn
    name: Install Dependencies
    command: yarn install --frozen-lockfile --non-interactive --cache-folder=~/.cache/yarn
  - &lint
    name: Lint
    command: yarn lint
  - &test
    name: Test
    command: yarn test



jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: date
      - run: *yarn
      - save_cache: *save-cache
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto-release
      - run: *lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto-release
      - run: *test
      - run:
          name: Send CodeCov Results
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_KEY

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto-release
      - run:
          name: Build
          command: yarn build
      - run:
          name: Check PR for semVer label
          command: yarn semver:check
      - persist_to_workspace:
          root: .
          paths:
            - .

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto-release
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Release
          command: yarn run release

  publishDocs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto-release
      - run:
          name: Publish Docs
          command: yarn docs:publish

workflows:
  version: 2
  build_and_test:
    jobs:
      - install

      - lint:
          requires:
            - install

      - test:
          requires:
            - install

      - build:
          requires:
            - install

      - release:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master

      - publishDocs:
          requires:
            - release
          filters:
            branches:
              only:
                - master
