version: 2

defaults: &defaults
  working_directory: ~/auto-release
  docker:
    - image: circleci/node:10.13.0-browsers
  environment:
    TZ: '/usr/share/zoneinfo/America/Los_Angeles'

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package.json checksum
            # when this file is changed, this key will fail
            - auto-release-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
            - auto-release-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - auto-release-{{ .Branch }}
            # Find the most recent cache used from any branch
            - auto-release-master
            - auto-release-
      - run: date
      - run:
          name: Install Dependencies
          command: npm i
      - save_cache:
          key: auto-release-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto-release
      - run:
          name: Lint
          command: yarn lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto-release
      - run:
          name: Test
          command: yarn test
      - run:
          name: Send CodeCov Results
          command: bash <(curl -s https://codecov.tools.a.intuit.com/bash) -t $CODECOV_KEY

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto-release
      - run:
          name: Build
          command: yarn build
      - run:
          name: Check PR for semVer label
          command: yarn semver:check
      - persist_to_workspace:
          root: .
          paths:
            - .

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto-release
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Release
          command: yarn run release

workflows:
  version: 2
  build_and_test:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/

      - lint:
          requires:
            - install
          filters:
            tags:
              only: /.*/

      - test:
          requires:
            - install
          filters:
            tags:
              only: /.*/

      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      # - release:
      #     requires:
      #       - build
      #       - lint
      #       - test
      #     filters:
      #       branches:
      #         only:
      #           - master
